<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW5030" failures="1" tests="1" name="pow test" time="0.001" errors="0" timestamp="8 Apr 2019 12:06:44 GMT">
  <testcase classname="test.java.PowTest" name="ctgTest" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [42.22425314473263] but found [32.0]">
      <![CDATA[java.lang.AssertionError: expected [42.22425314473263] but found [32.0]
	at test.java.PowTest.ctgTest(PowTest.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- ctgTest -->
</testsuite> <!-- pow test -->
